<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>StayZio Login</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">
<style>
:root{--navy:#0B1F3A;--navy2:#143A63;--teal:#00B8B8;--teal-dark:#009A9A;--teal-soft:#E8FBFB;--text:#3C4A5D;--text-strong:#223148;--muted:#7D8898;--placeholder:#B2BBC7;--line:#E3EAF0;--white:#fff;--danger:#DC3545;--shadow:0 28px 80px rgba(11,31,58,.16)}
*{box-sizing:border-box;margin:0;padding:0}html{scroll-behavior:smooth}body{font-family:Inter,-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;background:radial-gradient(circle at 14% 12%,rgba(0,184,184,.10),transparent 25%),radial-gradient(circle at 88% 18%,rgba(11,31,58,.08),transparent 28%),linear-gradient(180deg,#F8FCFD 0%,#fff 55%,#F5FBFB 100%);color:var(--text);min-height:100vh}a{text-decoration:none;color:inherit}button,input{font-family:inherit}.page{min-height:100vh;overflow:hidden}
.topbar{height:78px;background:rgba(255,255,255,.96);border-bottom:1px solid var(--line);position:sticky;top:0;z-index:20;box-shadow:0 3px 16px rgba(11,31,58,.05);backdrop-filter:blur(12px)}.topbar-inner{max-width:1180px;margin:auto;height:100%;display:flex;align-items:center;justify-content:space-between;padding:0 22px}.brand{display:flex;align-items:center}.brand img{width:165px;height:52px;object-fit:contain;object-position:left center}.nav{display:flex;align-items:center;gap:28px;font-size:12px;font-weight:700}.nav a{color:var(--navy);transition:.2s}.nav a:hover{color:var(--teal-dark)}.nav .outline{border:1px solid var(--navy);border-radius:999px;padding:11px 20px}.nav .outline:hover{background:var(--teal);border-color:var(--teal);color:#fff}.hamb{display:none;border:0;background:#fff;border-radius:14px;padding:11px;box-shadow:0 10px 25px rgba(0,0,0,.08);color:var(--navy)}
.hero{position:relative;padding:54px 22px 70px}.hero:before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 20% 8%,rgba(0,184,184,.09),transparent 28%),radial-gradient(circle at 88% 12%,rgba(11,31,58,.06),transparent 30%);pointer-events:none;animation:heroGlow 8s ease-in-out infinite alternate}@keyframes heroGlow{from{opacity:.65;transform:scale(1)}to{opacity:1;transform:scale(1.025)}}.hero-inner{max-width:1180px;margin:auto;position:relative;display:grid;grid-template-columns:1.05fr .95fr;gap:42px;align-items:center}.copy-panel{animation:copyIn .75s cubic-bezier(.2,.7,.2,1) both}@keyframes copyIn{from{opacity:0;transform:translateX(-28px)}to{opacity:1;transform:translateX(0)}}
.eyebrow{display:inline-flex;align-items:center;gap:8px;background:#fff;border:1px solid #BDEEEE;color:var(--teal-dark);padding:10px 14px;border-radius:999px;font-weight:900;font-size:13px;box-shadow:0 10px 22px rgba(0,184,184,.10);animation:floatBadge 4s ease-in-out infinite}@keyframes floatBadge{0%,100%{transform:translateY(0)}50%{transform:translateY(-4px)}}h1{font-size:64px;line-height:.98;letter-spacing:-2.4px;margin:22px 0 18px;color:var(--navy)}.lead{font-size:18px;line-height:1.75;color:#657184;max-width:570px}.hero-points{display:grid;grid-template-columns:repeat(3,1fr);gap:14px;margin-top:30px}.point{background:rgba(255,255,255,.92);border:1px solid var(--line);border-radius:20px;padding:16px;box-shadow:0 15px 35px rgba(11,31,58,.05);transition:.25s ease}.point:hover{transform:translateY(-4px);border-color:#CBEDED;box-shadow:0 20px 38px rgba(11,31,58,.08)}.point i{color:var(--teal);font-size:18px;margin-bottom:10px}.point strong{display:block;font-size:14px;color:var(--navy)}.point small{display:block;color:var(--muted);font-size:12px;margin-top:5px}
.visual{position:relative;min-height:640px;display:flex;align-items:flex-start;justify-content:flex-start}.red-card{position:absolute;right:0;top:20px;width:76%;height:490px;border-radius:40px;background:linear-gradient(135deg,var(--navy),var(--navy2));box-shadow:var(--shadow);overflow:hidden;animation:visualIn .85s .08s cubic-bezier(.2,.7,.2,1) both}@keyframes visualIn{from{opacity:0;transform:translateX(30px) scale(.98)}to{opacity:1;transform:translateX(0) scale(1)}}.red-card:before{content:"";position:absolute;inset:0;background:url('https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80') center/cover;opacity:.28;transform:scale(1.03);animation:imageDrift 14s ease-in-out infinite alternate}@keyframes imageDrift{from{transform:scale(1.03)}to{transform:scale(1.08) translate(-8px,-5px)}}.red-card:after{content:"";position:absolute;inset:0;background:linear-gradient(135deg,rgba(11,31,58,.90),rgba(0,184,184,.40))}
.phone-card{position:relative;left:0;margin-top:62px;width:420px;max-width:100%;background:rgba(255,255,255,.98);border-radius:34px;padding:28px;box-shadow:0 32px 90px rgba(11,31,58,.18);border:1px solid rgba(255,255,255,.92);z-index:2;animation:loginCardIn .85s .15s cubic-bezier(.18,.75,.2,1) both}@keyframes loginCardIn{0%{opacity:0;transform:translateY(26px) scale(.975)}100%{opacity:1;transform:translateY(0) scale(1)}}.login-head{text-align:center;margin-bottom:22px}.login-head img{width:145px;height:58px;object-fit:contain;margin:auto auto 10px;animation:logoPop .7s .45s ease both}@keyframes logoPop{from{opacity:0;transform:scale(.9)}to{opacity:1;transform:scale(1)}}.login-head h2{font-size:28px;letter-spacing:-.8px;color:var(--navy)}.login-head p{color:var(--muted);font-size:14px;margin-top:7px}
.tabs{display:grid;grid-template-columns:1fr 1fr;background:#F3F6F8;border-radius:16px;padding:5px;margin-bottom:18px}.tabs button{border:0;background:transparent;border-radius:12px;padding:12px;font-weight:900;color:#7B8490;cursor:pointer;transition:.22s}.tabs button.active{background:#fff;color:var(--teal-dark);box-shadow:0 8px 18px rgba(11,31,58,.06)}
.field{margin-bottom:14px}.field label{display:block;font-size:12px;font-weight:800;color:#8B97A7;margin-bottom:8px;text-transform:uppercase;letter-spacing:.07em}.input-wrap{display:flex;align-items:center;gap:10px;border:1.5px solid #DDE5EC;border-radius:16px;background:#fff;padding:0 14px;height:56px;transition:.22s}.input-wrap:focus-within{border-color:var(--teal);box-shadow:0 0 0 4px rgba(0,184,184,.10),0 10px 24px rgba(11,31,58,.04);background:#FCFFFF;transform:translateY(-1px)}.input-wrap>i,.field-icon{color:#54BFC1;font-size:16px;min-width:18px}.input-wrap input{border:0;outline:0;width:100%;font-size:16px;font-weight:500;color:var(--text-strong);background:transparent;caret-color:var(--teal);letter-spacing:.01em}.input-wrap input::placeholder{color:var(--placeholder);font-weight:500}.country{font-weight:800;border-right:1px solid #E7ECF1;padding-right:10px;color:#415068}.password-input{font-weight:500!important;letter-spacing:.04em!important}.password-input[type=text]{letter-spacing:.01em!important}.password-toggle{width:36px;height:36px;border:0;border-radius:11px;background:#F3FAFA;color:#6C7B8D;display:flex;align-items:center;justify-content:center;cursor:pointer;flex:0 0 auto;transition:.2s}.password-toggle:hover{color:var(--teal-dark);background:var(--teal-soft);transform:scale(1.04)}.forgot{display:flex;justify-content:flex-end;margin:-4px 0 14px;color:var(--teal-dark);font-size:13px;font-weight:800}.forgot:hover{text-decoration:underline}
.btn{width:100%;height:58px;border:0;border-radius:17px;background:linear-gradient(135deg,var(--teal),var(--teal-dark));color:#fff;font-size:16px;font-weight:900;box-shadow:0 18px 35px rgba(0,184,184,.24);cursor:pointer;transition:.22s;position:relative;overflow:hidden}.btn:after{content:"";position:absolute;top:-60%;left:-40%;width:36%;height:220%;background:rgba(255,255,255,.22);transform:rotate(18deg);transition:left .55s ease}.btn:hover{transform:translateY(-2px);box-shadow:0 22px 42px rgba(0,184,184,.28)}.btn:hover:after{left:120%}.btn:disabled{opacity:.6;cursor:not-allowed}.or{display:flex;align-items:center;gap:12px;margin:18px 0;color:#A1A7B2;font-size:13px}.or:before,.or:after{content:"";height:1px;background:#E7ECF1;flex:1}.google{height:52px;border:1.5px solid #E3E9EF;background:#fff;border-radius:16px;width:100%;font-weight:800;display:flex;align-items:center;justify-content:center;gap:10px;cursor:pointer;color:var(--navy);transition:.22s}.google:hover{border-color:#CBE8E8;background:#FBFFFF;transform:translateY(-1px);box-shadow:0 12px 25px rgba(11,31,58,.06)}.google i{color:#4285F4}.signup{text-align:center;margin-top:18px;color:#707784;font-size:14px}.signup b{color:var(--teal-dark)}
.otp-boxes{display:flex;align-items:center;justify-content:space-between;gap:8px;margin:12px 0 18px;width:100%}.otp-boxes input{width:48px;min-width:0;text-align:center;height:52px;border:1.5px solid #E3E9EF;border-radius:14px;font-weight:800;font-size:20px;color:var(--text-strong);background:#fff;box-shadow:0 8px 18px rgba(0,0,0,.035);transition:.2s}.otp-boxes input:focus{outline:none;border-color:var(--teal);box-shadow:0 0 0 4px rgba(0,184,184,.10);transform:translateY(-1px)}.otp-panel{margin-top:18px;padding:18px;background:#F3FCFC;border:1px solid #BDEEEE;border-radius:18px;animation:panelIn .28s ease both}@keyframes panelIn{from{opacity:0;transform:translateY(7px)}to{opacity:1;transform:translateY(0)}}.otp-meta{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:10px}.otp-title{font-size:12px;font-weight:900;color:#8491A1;text-transform:uppercase;letter-spacing:.08em}.resend{font-size:12px;font-weight:800;color:var(--teal-dark);cursor:pointer;background:none;border:none}.err-msg{color:var(--danger);font-size:12.5px;margin-top:6px;display:none}.test-mode{background:#fff8e1;border:1px solid #ffe082;border-radius:10px;padding:9px 12px;font-size:11.5px;color:#996400;margin-bottom:10px}.auth-panel{animation:authPanelIn .28s ease both}@keyframes authPanelIn{from{opacity:0;transform:translateY(7px)}to{opacity:1;transform:translateY(0)}}
.app-banner{max-width:1180px;margin:0 auto 60px;padding:0 22px}.app-card{background:var(--navy);color:#fff;border-radius:34px;padding:34px;display:flex;align-items:center;justify-content:space-between;gap:25px;box-shadow:0 22px 70px rgba(11,31,58,.18);overflow:hidden;position:relative}.app-card:before{content:"";position:absolute;right:-60px;top:-90px;width:260px;height:260px;border-radius:50%;background:rgba(0,184,184,.28);animation:orbFloat 7s ease-in-out infinite alternate}@keyframes orbFloat{from{transform:translate(0,0) scale(1)}to{transform:translate(-24px,20px) scale(1.08)}}.app-card h3{font-size:28px;margin-bottom:8px;color:#fff}.app-card p{color:#D6E0EA}.store-row{display:flex;gap:12px;position:relative}.store{border:1px solid rgba(255,255,255,.2);background:rgba(255,255,255,.08);color:#fff;border-radius:16px;padding:12px 18px;font-weight:900;display:flex;align-items:center;gap:10px}
@media(max-width:900px){.nav{display:none}.hamb{display:block}.hero{padding-top:30px;padding-bottom:44px}.hero-inner{grid-template-columns:1fr}.visual{min-height:auto;display:block}.red-card{display:none}.phone-card{position:relative;top:0;left:auto;width:100%;max-width:430px;margin:26px auto 0}.hero-points{grid-template-columns:1fr}h1{font-size:42px}.lead{font-size:16px}.app-card{flex-direction:column;text-align:center}.store-row{flex-wrap:wrap;justify-content:center}}@media(max-width:520px){.topbar{height:68px}.brand img{width:140px;height:44px}.hero{padding-left:14px;padding-right:14px;padding-bottom:34px}.phone-card{padding:18px;border-radius:26px}.login-head img{width:130px;height:52px}.login-head h2{font-size:24px}.input-wrap{height:52px}.btn{height:54px}h1{font-size:36px}.app-banner{padding:0 14px}.app-card{border-radius:24px;padding:25px 18px}.store{width:100%;justify-content:center}.otp-boxes{gap:6px}.otp-boxes input{width:42px;height:46px;font-size:18px;border-radius:12px}.otp-panel{padding:14px}}
</style>
</head>
<body>
<div class="page">
<header class="topbar"><div class="topbar-inner"><a class="brand" href="{{ route('index') }}"><img src="{{ asset('stayzio/images/stayzio-logo.png') }}" alt="StayZio"></a><nav class="nav"><a href="{{ route('index') }}">Home</a><a href="{{ route('vendor.signup') }}">List Hotel</a><a>Help & Support</a><a class="outline" href="{{ route('user.otp.show') }}">Login / Sign up</a></nav><button class="hamb" type="button" aria-label="Menu"><i class="fa-solid fa-bars"></i></button></div></header>
<section class="hero"><div class="hero-inner"><div class="copy-panel"><div class="eyebrow"><i class="fa-solid fa-clock"></i> Hourly hotel booking made simple</div><h1>Welcome back to StayZio.</h1><p class="lead">Login with mobile OTP or password and continue booking verified hourly hotels, couple-friendly stays, and short-stay rooms at the best price.</p><div class="hero-points"><div class="point"><i class="fa-solid fa-bolt"></i><strong>Pay by the hour</strong><small>3 hrs, 6 hrs, full day</small></div><div class="point"><i class="fa-solid fa-shield-heart"></i><strong>Safe stays</strong><small>Verified hotels only</small></div><div class="point"><i class="fa-solid fa-tags"></i><strong>Best offers</strong><small>Coupons and app deals</small></div></div></div>
<div class="visual"><div class="red-card"></div><div class="phone-card"><div class="login-head" id="loginHead"><img src="{{ asset('stayzio/images/stayzio-logo.png') }}" alt="StayZio"><h2>Welcome Back</h2><p>Login / Sign up to continue</p></div><div class="tabs" id="authTabs"><button class="active" type="button" onclick="switchTab('otp')">OTP</button><button type="button" onclick="switchTab('password')">Password</button></div>
<div id="otpForm" class="auth-panel"><input type="hidden" id="otpPhone"><div class="field" id="phoneFieldWrap"><label>Mobile Number</label><div class="input-wrap"><span class="country">+91</span><input id="inputPhone" maxlength="10" inputmode="numeric" autocomplete="tel" placeholder="Enter mobile number"></div><div class="err-msg" id="errPhone"></div></div><button class="btn" id="btnSendOtp" type="button" onclick="sendOtp()">Continue</button>
<div id="otpArea" class="otp-panel" style="display:none"><div class="otp-meta"><span class="otp-title" id="otpAreaTitle">Enter OTP</span><button class="resend" type="button" onclick="sendOtp()">Resend</button></div><div class="test-mode" id="testModeBanner" style="display:none"></div><div class="otp-boxes"><input maxlength="1" inputmode="numeric" autocomplete="one-time-code"><input maxlength="1" inputmode="numeric"><input maxlength="1" inputmode="numeric"><input maxlength="1" inputmode="numeric"><input maxlength="1" inputmode="numeric"><input maxlength="1" inputmode="numeric"></div><div class="err-msg" id="errOtp"></div><button class="btn" id="btnVerifyOtp" type="button" onclick="verifyOtp()">Verify & Login</button></div>
<div id="nameArea" class="otp-panel" style="display:none"><div class="otp-meta"><span class="otp-title">Welcome! What's your name?</span></div><div class="field" style="margin-top:10px"><div class="input-wrap"><i class="fa-regular fa-user field-icon"></i><input id="inputName" autocomplete="name" placeholder="Your full name"></div></div><div class="err-msg" id="errName"></div><button class="btn" id="btnCompleteSignup" type="button" onclick="completeSignup()">Create Account</button></div></div>
<form id="passwordForm" class="auth-panel" style="display:none" action="{{ route('user.login_submit') }}" method="POST" autocomplete="off">@csrf<div class="field"><label>Email / Mobile</label><div class="input-wrap"><i class="fa-regular fa-user field-icon"></i><input id="loginIdentity" name="email" type="text" autocomplete="off" autocorrect="off" autocapitalize="none" spellcheck="false" readonly onfocus="this.removeAttribute('readonly');" placeholder="Enter email or mobile"></div></div><div class="field"><label>Password</label><div class="input-wrap"><i class="fa-solid fa-lock field-icon"></i><input id="loginPassword" class="password-input" type="password" name="password" autocomplete="new-password" readonly onfocus="this.removeAttribute('readonly');" placeholder="Enter password"><button class="password-toggle" id="passwordToggle" type="button" onclick="toggleLoginPassword()" aria-label="Show password" aria-pressed="false"><i class="fa-regular fa-eye" id="passwordEyeIcon"></i></button></div></div><a class="forgot" href="{{ route('user.forget_password') }}">Forgot Password?</a><button class="btn" type="submit">Login</button></form>
<div class="or">or</div><a class="google" href="{{ route('user.login.google') }}"><i class="fa-brands fa-google"></i> Continue with Google</a><div class="signup" id="signupLine">Do not have an account? <b>It's automatic with OTP!</b></div></div></div></div></section>
<section class="app-banner"><div class="app-card"><div><h3>Download StayZio App</h3><p>Get exclusive short-stay deals, instant confirmation, and faster booking.</p></div><div class="store-row"><div class="store"><i class="fa-brands fa-google-play"></i> Google Play</div><div class="store"><i class="fa-brands fa-apple"></i> App Store</div></div></div></section></div>
<script>
function switchTab(tab){document.querySelectorAll('#authTabs button').forEach(function(b,i){b.classList.toggle('active',(tab==='otp'&&i===0)||(tab==='password'&&i===1));});var otpForm=document.getElementById('otpForm'),passwordForm=document.getElementById('passwordForm'),signupLine=document.getElementById('signupLine');otpForm.style.display=tab==='otp'?'block':'none';passwordForm.style.display=tab==='password'?'block':'none';signupLine.style.display=tab==='otp'?'none':'block';var shown=tab==='otp'?otpForm:passwordForm;shown.classList.remove('auth-panel');void shown.offsetWidth;shown.classList.add('auth-panel');if(tab==='password'){setTimeout(function(){var userInput=passwordForm.querySelector('input[name="email"]');if(userInput)userInput.focus();},80);}}
function toggleLoginPassword(){var input=document.getElementById('loginPassword'),icon=document.getElementById('passwordEyeIcon'),btn=document.getElementById('passwordToggle');if(!input||!icon||!btn)return;var willShow=input.type==='password';input.type=willShow?'text':'password';icon.classList.toggle('fa-eye',!willShow);icon.classList.toggle('fa-eye-slash',willShow);btn.setAttribute('aria-label',willShow?'Hide password':'Show password');btn.setAttribute('aria-pressed',willShow?'true':'false');input.focus();}
function showErr(id,msg){var el=document.getElementById(id);el.textContent=msg;el.style.display=msg?'block':'none';}
function sendOtp(){var phone=document.getElementById('inputPhone').value.trim();if(!/^[6-9][0-9]{9}$/.test(phone)){showErr('errPhone','Enter a valid 10-digit mobile number');return;}showErr('errPhone','');document.getElementById('otpPhone').value=phone;var btn=document.getElementById('btnSendOtp');btn.disabled=true;btn.textContent='Sending...';fetch('{{ route("user.otp.send") }}',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':'{{ csrf_token() }}'},body:JSON.stringify({phone:phone})}).then(function(r){return r.json();}).then(function(data){btn.disabled=false;btn.textContent='Continue';if(data.status==='success'){document.getElementById('phoneFieldWrap').style.display='none';btn.style.display='none';var banner=document.getElementById('testModeBanner');if(data.test_mode_otp){banner.style.display='block';banner.textContent='TEST MODE (Nettyfish not yet connected) — OTP: '+data.test_mode_otp;}else{banner.style.display='none';}document.querySelectorAll('#otpArea .otp-boxes input').forEach(function(d){d.value='';});document.getElementById('otpArea').style.display='block';document.querySelector('#otpArea .otp-boxes input').focus();}else{showErr('errPhone',data.message||'Could not send OTP, please try again');}}).catch(function(){btn.disabled=false;btn.textContent='Continue';showErr('errPhone','Something went wrong, please try again');});}
function verifyOtp(){var digits=document.querySelectorAll('#otpArea .otp-boxes input');var otp=Array.from(digits).map(function(d){return d.value;}).join('');if(otp.length!==6){showErr('errOtp','Enter all 6 digits');return;}showErr('errOtp','');var phone=document.getElementById('otpPhone').value;var btn=document.getElementById('btnVerifyOtp');btn.disabled=true;btn.textContent='Verifying...';fetch('{{ route("user.otp.verify") }}',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':'{{ csrf_token() }}'},body:JSON.stringify({phone:phone,otp:otp})}).then(function(r){return r.json();}).then(function(data){btn.disabled=false;btn.textContent='Verify & Login';if(data.status==='success'){if(data.is_new_user){document.getElementById('otpArea').style.display='none';document.getElementById('nameArea').style.display='block';}else{window.location.href=data.redirect;}}else{showErr('errOtp',data.message||'Invalid OTP');}}).catch(function(){btn.disabled=false;btn.textContent='Verify & Login';showErr('errOtp','Something went wrong, please try again');});}
function completeSignup(){var name=document.getElementById('inputName').value.trim();if(!name){showErr('errName','Please enter your name');return;}showErr('errName','');var phone=document.getElementById('otpPhone').value;var btn=document.getElementById('btnCompleteSignup');btn.disabled=true;btn.textContent='Creating account...';fetch('{{ route("user.otp.complete_signup") }}',{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':'{{ csrf_token() }}'},body:JSON.stringify({phone:phone,name:name})}).then(function(r){return r.json();}).then(function(data){if(data.status==='success'){window.location.href=data.redirect;}else{btn.disabled=false;btn.textContent='Create Account';showErr('errName',data.message||'Something went wrong');}}).catch(function(){btn.disabled=false;btn.textContent='Create Account';showErr('errName','Something went wrong, please try again');});}
function clearLoginCredentials(){var email=document.getElementById('loginIdentity'),password=document.getElementById('loginPassword'),icon=document.getElementById('passwordEyeIcon'),btn=document.getElementById('passwordToggle');if(email){email.value='';email.setAttribute('readonly','readonly');}if(password){password.value='';password.setAttribute('readonly','readonly');password.type='password';}if(icon){icon.classList.remove('fa-eye-slash');icon.classList.add('fa-eye');}if(btn){btn.setAttribute('aria-label','Show password');btn.setAttribute('aria-pressed','false');}}window.addEventListener('pageshow',function(){setTimeout(clearLoginCredentials,50);});document.addEventListener('DOMContentLoaded',function(){clearLoginCredentials();setTimeout(clearLoginCredentials,120);setTimeout(clearLoginCredentials,500);});document.querySelectorAll('#otpArea .otp-boxes input').forEach(function(input,idx,all){input.addEventListener('input',function(){this.value=this.value.replace(/\D/g,'').slice(0,1);if(this.value&&all[idx+1])all[idx+1].focus();});input.addEventListener('keydown',function(e){if(e.key==='Backspace'&&!this.value&&all[idx-1])all[idx-1].focus();});input.addEventListener('paste',function(e){var text=(e.clipboardData||window.clipboardData).getData('text').replace(/\D/g,'').slice(0,6);if(!text)return;e.preventDefault();text.split('').forEach(function(digit,i){if(all[i])all[i].value=digit;});if(all[Math.min(text.length,6)-1])all[Math.min(text.length,6)-1].focus();});});
</script>
</body>
</html>
